version: "2.0"
services: 
  key-value-store:
    build: .
    #container_name: dynamo
    environment:
      GRAPHITE_HOST: 'localhost'
      COLLECTD_HOST: 'localhost'
      RSYSLOG_HOST: 'localhost'
      GRAPHITE_IP: '192.168.122.84'
      COLLECTD_IP: '192.168.122.84'
      RSYSLOG_IP: '192.168.122.84'
    #ports:
      #- "8080:8080"
    #Consul ports
      #- "8300"
      #- "8301"
      #- "8302"
      #- "8400"
      #- "8500"
      #- "8600"
    #Dynamo ports
      #- "5550"
    restart: always
    network_mode: "bridge"
    #net: dynamo-net
