consul_server:
  build: "."
  #image: "voxxit/consul"
  environment:
    NODE1_IP: "${NODE1_IP}"
    NODE2_IP: "${NODE2_IP}"
    RSYSLOG_IP: "${RSYSLOG_IP}"
    LOGGING_IP: "${LOGGING_IP}"
    HOST_IP: "${HOST_IP}"
    HOSTNAME: "${HOSTNAME}"
  volumes:
    - "/var/log/consul"
    - "/etc/consul.d"
  net: "host"
  command: ["/usr/bin/start-consul.sh"]
