consul_server:
  build: "."
  container_name: "consul"
  environment:
    NODE1_IP: "${NODE1_IP}"
    NODE2_IP: "${NODE2_IP}"
    HOST_IP: "${HOST_IP}"
  volumes:
    - "/var/log/consul"
    - "/etc/consul.d"
  net: "host"
