version: '2'
services: 
  consul_server:
     build: ../service-discovery
     volumes:
        - "/var/log/consul"
        - "/etc/consul.d"
     container_name: "consul-server"
     hostname: "consul-server.weave.local"
     network_mode: "weave"
     restart: always
  haproxy-consul-template:
     build: ../proxy-loadbalancer
     container_name: "haproxy"
     hostname: "haproxy.weave.local"
     network_mode: "weave"
     restart: always
  logging:
     build: ../logging
     restart: always
     container_name: "logging"
     hostname: "logging.weave.local"
     network_mode: "weave"
      
